---
# hosts
- name: add server to web group
  delegate_to: 127.0.0.1
  bx_conf:
    hostname={{ inventory_hostname }}
    state=update
    group=web
  tags: ansible_hosts

# group vars
- name: update bitrix-mysql group
  delegate_to: 127.0.0.1
  bx_conf:
    group=mysql
    state=update
    cluster_login={{ cluster_login }}
    cluster_password_file={{ cluster_password_file }}
    replica_login={{ replica_login }}
    replica_password_file={{ replica_password_file }}
  tags: ansible_hosts
  
- name: update bitrix-web group
  delegate_to: 127.0.0.1
  bx_conf:
    group=web
    state=update
    web_mysql_login={{ cluster_login }}
    web_mysql_password_file={{ cluster_password_file }}
    web_mysql_server={{ master_server }}
    fstype={{ fstype }}
  tags: ansible_hosts

- name: web cluster set to enable
  delegate_to: 127.0.0.1
  bx_conf:
    group={{ item }}
    state=update
    cluster_web_configure=enable
  with_items:
    - hosts
    - web
  tags: ansible_hosts
