---
# restart network
- name: restart network
  service:
    name=network
    state=restarted
  tags: service

- name: restart nginx
  service:
    name=nginx
    state=restarted
  tags: service

- name: restart httpd
  service:
    name=httpd
    state=restarted
  tags: httpd

- name: restart mysqld
  service:
    name=mysqld
    state=restarted
  tags: mysqld

